language: rust

git:
  depth: 1

os:
  - linux
  - osx
  - windows

rust:
  - 1.36.0
  - stable

matrix:
  fast_finish: true
  include:
    - name: "Clippy Linux"
      os: linux
      env: CLIPPY=true
      rust: stable
    - name: "Clippy OSX"
      os: osx
      env: CLIPPY=true
      rust: stable
    - name: "Clippy Windows"
      os: windows
      env: CLIPPY=true
      rust: stable

install:
  - if [ "$CLIPPY" == "true" ]; then rustup component add clippy; fi

script:
  - if [ "$CLIPPY" == "true" ]; then cargo clippy; fi
  - if [ "$CLIPPY" != "true" ]; then cargo test; fi
